criterion:
- kwargs:
    weight: 1.0
  name: FeatureMSELoss
  type: FeatureMSELoss
dataset:
  batch_size: 8
  image_reader:
    kwargs:
      color_mode: RGB
      image_dir: ./data/MVTec-AD/mvtec_anomaly_detection
    type: opencv
  input_size:
  - 224
  - 224
  pixel_mean:
  - 0.485
  - 0.456
  - 0.406
  pixel_std:
  - 0.229
  - 0.224
  - 0.225
  test:
    meta_file: ./data/MVTec-AD/test.json
  train:
    hflip: false
    meta_file: ./data/MVTec-AD/train.json
    rebalance: false
    rotate: false
    vflip: false
  type: custom
  workers: 4
evaluator:
  key_metric: mean_pixel_auc
  metrics:
    auc:
    - name: std
    - kwargs:
        avgpool_size:
        - 16
        - 16
      name: max
    - name: pixel
  save_dir: result_eval_temp
  vis_compound:
    max_score: null
    min_score: null
    save_dir: ./tools/vis_compound
frozen_layers:
- backbone
net:
- frozen: true
  kwargs:
    outlayers:
    - 3
    pretrained: true
    spiking_neuron: IFNode
    timesteps: 4
  name: backbone
  type: models.backbones.spiking_resnet18
- kwargs:
    activation: relu
    channel_memory_size: 256
    dim_feedforward: 1024
    dropout: 0.1
    feature_jitter:
      prob: 1.0
      scale: 20.0
    feature_size:
    - 14
    - 14
    hidden_dim: 256
    initializer:
      method: xavier_uniform
    neighbor_mask:
      mask:
      - false
      - false
      - false
      neighbor_size:
      - 7
      - 7
    nhead: 8
    normalize_before: false
    num_decoder_layers: 4
    num_encoder_layers: 4
    pos_embed_type: learned
    save_recon:
      save_dir: result_recon
    spatial_memory_size: 256
    timesteps: 4
  name: reconstruction
  prev: backbone
  type: models.reconstructions.SpikeDrivenUniAD
port: 11111
random_seed: 133
saver:
  always_save: false
  auto_resume: true
  load_path: null
  log_dir: log/
  save_dir: checkpoints/
trainer:
  clip_max_norm: 0.1
  lr_scheduler:
    kwargs:
      gamma: 0.1
      step_size: 500
    type: StepLR
  max_epoch: 500
  optimizer:
    kwargs:
      betas:
      - 0.9
      - 0.999
      lr: 0.0001
      weight_decay: 0.0001
    type: AdamW
  print_freq_step: 100
  tb_freq_step: 1
  val_freq_epoch: 10
version: v1.0.0
wandb:
  api_key: 0f2ca680372a916c31aab5ede7bbefab410fe503
  dir: null
  enabled: false
  entity: null
  group: null
  job_type: train
  login: true
  mode: online
  name: bottle_zscore_sigmol_500_256_256_0mse_1spatial_mse_3non_beta2
  notes: UniAD with Spatial Region Focal Loss (pure) on MVTec-AD dataset - Local Training
  project: UniAD-MVTec-single
  resume: allow
  run_id: null
  tags:
  - mvtec
  - anomaly-detection
  - spatial-focal-loss
  - local
