wandb:
  enabled: false
  project: UniAD-MVTec-single
  entity: null
  name: local_500_256_256_0.4mse_0.6spatial_mse_3non_beta2
  tags:
    - mvtec
    - anomaly-detection
    - spatial-focal-loss
    - local
  notes: UniAD with Spatial Region Focal Loss (pure) on MVTec-AD dataset - Local Training
  mode: online
  group: null
  job_type: train
  resume: allow
  run_id: null
  dir: null
  login: true
  api_key: 0f2ca680372a916c31aab5ede7bbefab410fe503

version: v1.0.0
random_seed: 133
port: 11111

dataset:
  type: custom
  image_reader:
    type: opencv
    kwargs:
      image_dir: ./data/MVTec-AD/mvtec_anomaly_detection
      color_mode: RGB
  train:
    meta_file: ./data/MVTec-AD/train.json
    rebalance: false
    hflip: false
    vflip: false
    rotate: false
  test:
    meta_file: ./data/MVTec-AD/test.json
  input_size:
    - 224
    - 224
  pixel_mean:
    - 0.485
    - 0.456
    - 0.406
  pixel_std:
    - 0.229
    - 0.224
    - 0.225
  batch_size: 8
  workers: 4

criterion:
  - name: FeatureMSELoss
    type: FeatureMSELoss
    kwargs:
      weight: 1.0
      # mse_weight: 0 # 40% MSE for stability
      # spatial_focal_weight: 1 # 60% Spatial Focal for performance
      # beta: 2 # Moderate focusing strength
      # epsilon: 0.001
      # loss_type: mse
      # region_size: 3 # 3x3 regions
      # overlap: False

trainer:
  max_epoch: 500
  clip_max_norm: 0.1
  val_freq_epoch: 10
  print_freq_step: 100
  tb_freq_step: 1
  lr_scheduler:
    type: StepLR
    kwargs:
      step_size: 500
      gamma: 0.1
  optimizer:
    type: AdamW
    kwargs:
      lr: 0.0001
      betas:
        - 0.9
        - 0.999
      weight_decay: 0.0001

saver:
  auto_resume: true
  always_save: false
  load_path: null
  save_dir: checkpoints/
  log_dir: log/

evaluator:
  save_dir: result_eval_temp
  key_metric: mean_pixel_auc
  metrics:
    auc:
      - name: std
      - name: max
        kwargs:
          avgpool_size:
            - 16
            - 16
      - name: pixel
  vis_compound:
    save_dir: ./tools/vis_compound
    max_score: null
    min_score: null

frozen_layers:
  - backbone

net:
  - name: backbone
    type: models.backbones.spiking_resnet18
    frozen: true
    kwargs:
      pretrained: true
      outlayers:
        # - 1
        # - 2
        - 3
        # - 4
      spiking_neuron: IFNode
      # time_steps: 4
  # - name: neck
  #   prev: backbone
  #   type: models.necks.MFCN
  #   kwargs:
  #     outstrides:
  #       - 16
  - name: reconstruction
    prev: backbone
    type: models.reconstructions.SpikeDrivenUniAD
    kwargs:
      time_steps: 4
      pos_embed_type: learned
      hidden_dim: 256
      nhead: 8
      num_encoder_layers: 4
      num_decoder_layers: 4
      dim_feedforward: 1024
      feature_size:
        - 14
        - 14
      dropout: 0.1
      activation: relu
      normalize_before: false
      # memory_mode: both # Options: 'channel', 'spatial', 'both', 'none'
      # fusion_mode: concat # Options: 'concat', 'add', 'multiply', 'attention', 'gate'
      channel_memory_size: 256
      spatial_memory_size: 256
      feature_jitter:
        scale: 20.0
        prob: 1.0
      neighbor_mask:
        neighbor_size:
          - 7
          - 7
        mask:
          - false
          - false
          - false
      save_recon:
        save_dir: result_recon
      initializer:
        method: xavier_uniform
